ALTER TABLE 
MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

DELIMITER $$
CREATE TRIGGER set_pht_time BEFORE UPDATE ON users
FOR EACH ROW
BEGIN
  SET NEW.updated_at = UTC_TIMESTAMP() + INTERVAL 8 HOUR;
END$$
DELIMITER ;